### PR TITLE
Prometheus exporter endpoint

### LINKED ISSUE #21: Feature preview/discussion: Prometheus metrics
Hello, 

for better monitoring and adjusting settings i have implemented some Prometheus monitoring and a Grafana dashboard:
Screenshot 2023-12-18 at 22-44-51 Onlytrains - Dashboards - Grafana

https://snapshots.raintank.io/dashboard/snapshot/CprwsU4x2nlsCF7pZYsJMyS0D4YOkkhP

What are your thoughts? I would upstream it, though it does introduce dependencies to https://github.com/prometheus/client_golang/. The added code is pretty small, and the Prometheus endpoint would be off by default.

### PR DESCRIPTION
**Pull request by clonejo**
The Grafana dashboard diffs are a bit of a pain to clean up, so some fixups and changes are relegated to the last commit.

I hope the downgrade of the Go version in go.sum to 1.20 is OK, that is what Fedora ships. The version in the Makefile is unchanged, ofc.

Fixes #21.

### CODE REVIEW

**Review by jo-m — CHANGES_REQUESTED** [review]
Thank you!

My comments:
- declaring Go 1.20 in go.mod seems to be no problem
- I am a bit sceptical about the global state/variables, but I guess this seems to be the way to do it according to the prometheus guide, and it also kind of makes sense
- CI/linting does not pass with your changes, you should be able to reproduce that locally via `make docker_lint`
- I'd move the Grafana JSON file somewhere else, e.g. top level into a new grafana/ directory.
- Also, a short paragraph in the readme about the Prometheus endpoint and dashboard JSON would be nice. 2 lines are enough, just to make it discoverable.

**Comment by clonejo** [comment]
> I am a bit sceptical about the global state/variables, but I guess this seems to be the way to do it according to the prometheus guide, and it also kind of makes sense

An alternative could be to intersperse the prometheus variables/functions more with the files they instrument.


> CI/linting does not pass with your changes, you should be able to reproduce that locally via `make docker_lint`

Whoops. Fixed. 


> I'd move the Grafana JSON file somewhere else, e.g. top level into a new grafana/ directory.

done


> Also, a short paragraph in the readme about the Prometheus endpoint and dashboard JSON would be nice. 2 lines are enough, just to make it discoverable.

done

**Comment by jo-m** [comment]
Thanks! Shall I merge it as is?

**Comment by clonejo** [comment]
> Thanks! Shall I merge it as is?

go ahead!

Typically i mark as draft if it's not ready for merge.

**Pull request merged**
