### PR TITLE
introduce editorconfig

### PR DESCRIPTION
**Pull request by clonejo**
Feel free to nitpick the indent choices, i just would like to have this so my editor is configured correctly. Settings should already align with existing code.

### CODE REVIEW

**Comment by jo-m** [comment]
Hm, what editor are you using? At least for Go, which is 90% of the files in here, formatting is enforced by gofmt anyways.

**Comment by clonejo** [comment]
Neovim. And i don't have gofmt set up, since i rarely work with Go. I guess i should set it up …

**Comment by jo-m** [comment]
Alright!

**Review by jo-m — APPROVED** [review]

**Comment by clonejo** [comment]
Feel free to merge. (I can't since "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.")

**Comment by jo-m** [comment]
ah, didnt realize

**Pull request merged**
